services:
  media-organiser:
    build: .
    container_name: media_organiser
    restart: unless-stopped
    environment:
      IMPORT_DIR: /data/import
      LIB_DIR: /data/library
    ports:
      - "6767:6767"
    volumes:
      - /data/import:/data/import
      - /data/content:/data/library